// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLDRKUqkuMbBi4m2VUVSYqsUlOtq88ykc',
    appId: '1:295942428827:web:cc888ae9dcd60cd5900e3e',
    messagingSenderId: '295942428827',
    projectId: 'example-f131a',
    authDomain: 'example-f131a.firebaseapp.com',
    storageBucket: 'example-f131a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVH9oF9OLYIkixbeVaGkSVGnMkT6-3NKQ',
    appId: '1:295942428827:android:e954436a38d92980900e3e',
    messagingSenderId: '295942428827',
    projectId: 'example-f131a',
    storageBucket: 'example-f131a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRcAeqHeDurk2qYIXc6cCbEuech1ZqIJ8',
    appId: '1:295942428827:ios:d39d09ed867f4695900e3e',
    messagingSenderId: '295942428827',
    projectId: 'example-f131a',
    storageBucket: 'example-f131a.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRcAeqHeDurk2qYIXc6cCbEuech1ZqIJ8',
    appId: '1:295942428827:ios:d39d09ed867f4695900e3e',
    messagingSenderId: '295942428827',
    projectId: 'example-f131a',
    storageBucket: 'example-f131a.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
